name: Build EddictwareELEC image in container

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to run against'
        required: true
        type: choice
        options:
          - bookworm
          - jammy
          - noble
          - plucky
        default: noble
  push:
    branches: [ "master-entw" ]
    paths-ignore: &exclude_paths # set YAML anchors for reuse
      - '*.*'
      - '.github/actions/container-actions/**/*.yml'
      - '.github/workflows/**/*.yml'
      - '!.github/workflows/build-EddictwareELEC-in-container.yml'
      # - '.github/workflows/build-docker-image.yml'
      # - '.github/workflows/schedule-jobs.yml'
      - 'tools/docker/**'
  pull_request:
    branches: [ "master-entw" ]
    paths-ignore: *exclude_paths

run-name: ${{ format('{0} ({1} - {2})', github.workflow, inputs.environment || 'noble', github.event_name) }}

env:
  DistroCodeName: ${{ inputs.environment || 'noble' }}
  BUILDER_NAME: ${{ github.repository_owner }}
  BUILDER_VERSION: ""
  BUILD_BASE: ""
  EE_Distro: EddictwareELEC
  EE_Project: RPi
  EE_Device: RPi4
  EE_Arch: aarch64
  # EE_Distro_tag: ""
  EE_image_pathfilename: ""
  EE_image_filename: ""
  NB_CORES: 1
  GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  # HOME: ""

jobs:
  pre-build:
    name: Pre-build
#    runs-on: github
    runs-on: blacksmith-4vcpu-ubuntu-2404
    if: github.event.head_commit.author.username != '${{ github.repository_owner }}' || github.event.head_commit.message == 'Merge branch ''LibreELEC:master'' into master-entw' || github.event_name == 'workflow_dispatch'
      # && github.event_name != 'pull_request' && github.event_name != 'workflow_dispatch'
    env:
      BUILDKIT_PROGRESS: 'auto' #'plain' 'quiet'
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      HOME: ""
    steps:
    - name: Checkout repository scripts
      uses: actions/checkout@v5
      with:
        ref: ${{ github.event.repository.default_branch }}
        clean: false # otherwise .ccache subfolder gets deleted
        show-progress: true
        set-safe-directory: true # this is the default, but just to be sure
        sparse-checkout: .github/actions/scripts
#        sparse-checkout-cone-mode: false
#        path: .
#        filter: .github/actions/scripts

    - name: Initialize environment
      id: set-multi
      shell: bash
      run: |
        .github/actions/scripts/set_multi.sh ${{ runner.temp }}
        .github/actions/scripts/set_multi.sh

    - name: Checkout repository
      uses: actions/checkout@v5
      with:
        ref: 'master-entw'
        clean: false # otherwise .ccache subfolder gets deleted
        show-progress: false
        set-safe-directory: true # this is the default, but just to be sure

  repo-vars:
    name: Repo-vars
    needs: pre-build
    runs-on: blacksmith-4vcpu-ubuntu-2404
    permissions:
      actions: write
    env:
      GH_TOKEN: ${{ secrets.GH_RUNNER_TOKEN }}
      HOME: ""
    outputs:
      output_set_builder_version: ${{ steps.get-env-vars.outputs.output_set_builder_version }}
      output_get_pwd: ${{ steps.get-env-vars.outputs.output_get_pwd }}
      output_get_cpu_info: ${{ steps.get-env-vars.outputs.output_get_cpu_info }}
      output_get_distro_tag: ${{ steps.compose-image-tag.outputs.EE_Distro_tag }}
      EE_Test: ${{ steps.env-test.outputs.EE_Test }}
    steps:
    - name: Initialize environment
      id: set-multi
      shell: bash
      run: |
        .github/actions/scripts/set_multi.sh ${{ runner.temp }}
        .github/actions/scripts/set_multi.sh

    - uses: ./.github/actions/composite-actions/init-env-vars
      id: get-env-vars
      name: Init environment variables
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Compose image tag
      id: compose-image-tag
      shell: bash
      run: |
        fqdn=$(echo "${{ secrets.REGISTRY_FQDN }}" | sed 's/./& /g' | sed 's/ //g')
        dTag="$fqdn/${{ github.repository_owner }}/${{ env.DistroCodeName }}"
        # Use ,, to convert all characters to lowercase
        echo "EE_Distro_tag=${dTag,,}" | sudo tee -a $GITHUB_OUTPUT

      # # var1=$(echo "${{ secrets.REGISTRY_FQDN }}" | sed 's/./& /g')
      #   # echo "spaced: $var1"
      #   x=$(echo "${{ github.event.repository.full_name }}" | sed 's/./& /g' | sed 's/ //g')
      #   echo "repository_fullname: $x"
      #   exit 1
      #   # unspaced=$(echo "$var1" | tr -d ' ')
      #   unspaced=$(echo "${{ secrets.REGISTRY_FQDN }}" | sed 's/./& /g' | sed 's/ //g')
      #   # echo "::add-mask::$unspaced"
      #   echo "unspaced: $unspaced" # | sudo tee -a $GITHUB
      #   exit 1

    - name: Test
      id: env-test
      shell: bash
      run: |
        echo "EE_Test=$(echo "${{ secrets.REGISTRY_FQDN }}" | sed 's/./& /g' | sed 's/ //g' | tr '[:upper:]' '[:lower:]')" | sudo tee -a $GITHUB_OUTPUT
        # echo "EE_Distro_tag: $EE_Distro_tag"
        # echo "EE_Distro_tag2: ${{ env.EE_Distro_tag }}"
        # echo "EE_Distro_tag3: ${{ needs.repo-vars.outputs.output_get_distro_tag }}"
        # exit 1
    - name: Get EE_Test
      env:
        EE_DT: ${{ steps.compose-image-tag.outputs.EE_Distro_tag }}
        EE_Test: ${{ steps.env-test.outputs.EE_Test }}
      shell: bash
      run: |
        echo "The selected EE_DT is ${EE_DT}"
        echo "The selected EE_Test is ${EE_Test}"


  repo-login:
    name: Repo-login
    needs: repo-vars
    runs-on: blacksmith-4vcpu-ubuntu-2404
    permissions:
      actions: write
    env:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      HOME: ""
    steps:
    - name: Initialize environment
      id: set-multi
      shell: bash
      run: |
        .github/actions/scripts/set_multi.sh ${{ runner.temp }}
        .github/actions/scripts/set_multi.sh

    - name: Login to (private) Registry
      uses: docker/login-action@v3
      with:
        registry: ${{ secrets.REGISTRY_FQDN }}
        username: ${{ secrets.REGISTRY_USER }}
        password: ${{ secrets.REGISTRY_PWD }}

    - name: Prepare build directory
      id: prepare-build-dir
      shell: bash
      env:
        EE_DT: ${{ needs.repo-vars.outputs.output_get_distro_tag }}
        EE_Test: ${{ needs.repo-vars.outputs.EE_Test }}
      run: |
        echo "EE_DT: ${EE_DT}"
        echo "EE_Test: ${EE_Test}"
        echo "curdir: $PWD"
        chown -R docker:docker $PWD

        # docker login --username ${{ vars.DOCKERHUB_USERNAME }} --password ${{ secrets.DOCKERHUB_TOKEN }}
        # if [ "$(docker ps -aq -f status=exited -f name=build${{ env.EE_Distro }}.${{ env.DistroCodeName }})" ]; then
        #     # cleanup
        #     docker rm --force --volumes "build${{ env.EE_Distro }}.${{ env.DistroCodeName }}"
        # fi

  build:
    name: Build
    runs-on: blacksmith-4vcpu-ubuntu-2404
    needs:
      - repo-vars
      - repo-login
    env:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      HOME: ""
      BUILDER_VERSION: ${{ needs.repo-vars.outputs.output_set_builder_version }}
      EE_Distro_tag: ${{ needs.repo-vars.outputs.EE_Test }}
      EE_DT: ${{ needs.repo-vars.outputs.output_get_distro_tag }}
      EE_Test: ${{ needs.repo-vars.outputs.EE_Test }}
      NB_CORES: ${{ needs.repo-vars.outputs.output_get_cpu_info }}
    container:
      options: --user docker --log-driver none --workdir /build # --user root
      image: $EE_DT:latest
      credentials:
        username: ${{ secrets.REGISTRY_USER }}
        password: ${{ secrets.REGISTRY_PWD }}
      env:
        DISABLE_COLORS: yes
        LOGCOMBINE: fail
        MTIMMEDIATE: no
        DEBUG: yes
        LOCAL_CCACHE: yes
        MTDEBUG: yes
        MTVERBOSE: yes
        MTPROGRESS: yes
        DISTRO: ${{ env.EE_Distro }}
        PROJECT: ${{ env.EE_Project }}
        DEVICE: ${{ env.EE_Device }}
        ARCH: ${{ env.EE_Arch }}
        BUILDER_NAME: ${{ env.BUILDER_NAME }}
        BUILDER_VERSION: ${{ env.BUILDER_VERSION }}
        BUILD_BASE: "build.${{ env.DistroCodeName }}"
      volumes:
        - ${{ needs.repo-vars.outputs.output_get_pwd }}:/build:rw
    steps:
    - name: Initialize environment
      id: set-multi
      shell: bash
      run: |
        .github/actions/scripts/set_multi.sh ${{ runner.temp }}
        .github/actions/scripts/set_multi.sh

    - name: Build ${{ env.EE_Distro }} image
      run: |
        NB_CORES=${{ env.NB_CORES }}
        [ "$NB_CORES" -lt 1 ] && NB_CORES=1
        echo "NB_CORES=$NB_CORES"
        # run the build
        export
        # exit 1
        make -j$((NB_CORES+1)) -l${NB_CORES} image

  post-build:
    name: Post-build
    runs-on: blacksmith-4vcpu-ubuntu-2404
    needs: build
    steps:
    - name: Copy built ${{ env.EE_Distro }} image to archive
      id: archive-image
      run: |
        debug=true
        [ "$debug" = true ] && echo "[pwd]: $PWD"
        if [ -d $PWD/target ]; then
          lines=$(find $PWD/target -maxdepth 1 -type f -iname "${{ env.EE_Distro }}-${{ env.EE_Device }}.${{ env.EE_Arch }}*.img.gz" 2>/dev/null | wc -l)
          [ "$debug" = true ] && echo "[lines]: $lines"
          if [ $lines -ne 0 ]; then
            pathfilename=$(ls -t $PWD/target/${{ env.EE_Distro }}-${{ env.EE_Device }}.${{ env.EE_Arch }}*.img.gz | head --lines=1)
            [ "$debug" = true ] && echo "[EE_image_pathfilename]: $pathfilename"
            echo "EE_image_pathfilename=$pathfilename" | sudo tee -a $GITHUB_OUTPUT
            filename="${pathfilename##*/}"
            [ "$debug" = true ] && echo "[EE_image_filename]: $filename"
            echo "EE_image_filename=$filename" | sudo tee -a $GITHUB_OUTPUT
            if [ ! -d /root/target_archive ]; then
              mkdir --parents "/root/target_archive"
            fi
            if [ "$(cp "$pathfilename" "/root/target_archive")" ]; then # --update=older
              echo "Copied built image to /root/target_archive"
            else
              echo "No newer built image to copy to /root/target_archive"
            fi
          else
            echo "No built image found in target directory, skipping copy."
          fi
        else
          echo "No target directory found, skipping copy of built image."
        fi

    - name: Upload built ${{ env.EE_Distro }} image
      id: upload-image
      if: ${{ steps.archive-image.outputs.EE_image_pathfilename }} != ''
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      uses: actions/upload-artifact@v4
      with:
        name: "${{ steps.archive-image.outputs.EE_image_filename }}"
        path: "${{ steps.archive-image.outputs.EE_image_pathfilename }}"

  secrets:
    name: Accessing JSON secret
    permissions: write-all
    runs-on: blacksmith-4vcpu-ubuntu-2404 #ubuntu-latest
    needs: post-build
    env:
      encSCP_INFO: ${{ secrets.SCP_INFO }}
    steps:
      - name: Create JQ filter file
        run: |
          # quoted 'EOF' to prevent variable expansion when creating the file
          cat <<'EOF' > "${{ runner.temp }}/filter.jq"
          # filter.jq
          to_entries[]                                      # 1. Iterate over top-level keys (e.g., "red", "green")
          | . as {key: $parent, value: $v}                  # 2. Assign parent key and its value
          | ($v | if type == "array" then .[] else . end)   # 3. Normalize: if value is array, iterate; else, use as-is
          | to_entries[]                                    # 4. Iterate over each child key-value pair
          | "\($parent)_\(.key)=\(.value)"                  # 5. Format as "parent.child=value"
          EOF

      - name: Decode Secrets
        id: decode-secrets
        run: |
          if [ ! -x "$(command -v jq)" ]; then
            export DEBIAN_FRONTEND="noninteractive"
            echo "jq not found, installing..."
            sudo apt-get update
            sudo apt-get install -y jq
          fi

          echo "${{ env.encSCP_INFO }}" |
            base64 --decode |
            jq --raw-output --from-file ${{ runner.temp }}/filter.jq |
          while read line; do
            option="${line%%=*}"
            value="${line#*=}"
            echo "::add-mask::$value";
            echo "$option=$value" >> $GITHUB_ENV;
          done
          rm -f ${{ runner.temp }}/filter.jq

      - name: Decode connection_key
        id: decode-connection-key
        run: |
          value=$(printf '%s' "$connection_key" | base64 -d)
          escaped_value=$(printf '%s' "$value" | sed 's/%/%25/g; s/\r/%0D/g; s/$/%0A/' | tr -d '\n' | sed 's/%0A$//')
          echo "::add-mask::$escaped_value";
          {
            echo 'decoded_key<<EOF'
            echo "$escaped_value"
            echo 'EOF'
          } >> $GITHUB_OUTPUT

      - name: Echo out a GitHub Actions Secret to the logs
        id: unescape-connection-key
        run: |
          unescaped_value=$(printf '%s' "${{ steps.decode-connection-key.outputs.decoded_key }}" | sed 's/%25/%/g; s/%0D/\r/g; s/%0A/\n/g')
          echo "::add-mask::$unescaped_value";
          echo "connection_keyX=$unescaped_value" >> $GITHUB_OUTPUT;
          # echo "Trick to echo GitHub Actions Secret:"
          # echo "$unescaped_value" | sed 's/./& /g' | awk '{print substr($0,1,100);exit}'
          # echo "$connection_port" | sed 's/./& /g'

      - name: Copy ${{ env.EE_Distro }} image via SCP
        uses: appleboy/scp-action@v1
        with:
          host: ${{ steps.decode-secrets.outputs.connection_host }}
          port: ${{ steps.decode-secrets.outputs.connection_port }}
          username: ${{ steps.decode-secrets.outputs.connection_username }}
          key: ${{ steps.unescape-connection-key.outputs.connection_keyX }}
          fingerprint: ${{ steps.decode-secrets.outputs.connection_fingerprint }}
          protocol: ${{ steps.decode-secrets.outputs.connection_protocol }}
          source: ${{ steps.archive-image.outputs.EE_image_pathfilename }}
          target: ${{ steps.decode-secrets.outputs.transfer_target }}
