name: Build Container for building EddictwareELEC images

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to run against'
        required: true
        # type: environment
        type: choice
        options:
          - bookworm
          - jammy
          - noble
          - plucky
        default: noble
  # deployment:
  push:
    branches: [ "master-entw" ]
    paths: &include_paths
      - 'tools/docker/noble/Dockerfile'

run-name: '${{ github.workflow }} (${{ github.event.inputs.environment }})'

env:
  DistroCodeName: ${{ inputs.environment }}

jobs:
  build:
#    runs-on: github
    runs-on: blacksmith-4vcpu-ubuntu-2404
    env:
      BUILDKIT_PROGRESS: 'auto' #'plain' 'quiet'
    steps:

    -
      name: Get docker guid
      id: get-docker-guid
      run: |
        echo "docker-guid=$(id -u docker)" >> $GITHUB_OUTPUT
      shell: bash

    -
      name: Compose image tag
      id: compose-image-tag
      run: |
        dTag="${{ secrets.REGISTRY_FQDN }}/${{ github.repository_owner }}/${{ env.DistroCodeName }}"
        # Use ,, to convert all characters to lowercase
        echo "EE_Distro_tag=${dTag,,}" >> $GITHUB_OUTPUT
      shell: bash

    -
      name: Log in to (local/private) registry
      uses: docker/login-action@v3
      with:
        registry: "${{ secrets.REGISTRY_FQDN }}"
        username: ${{ secrets.REGISTRY_USER }}
        password: ${{ secrets.REGISTRY_PWD }}

    -
      name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
      with:
        name: builder-eddictwareelec
        version: latest
        keep-state: true
        cleanup: false
        # https://github.com/moby/buildkit/blob/master/docs/buildkitd.toml.md
        buildkitd-config-inline: |
          debug = false
          [registry."${{ secrets.REGISTRY_FQDN }}"]
            http = false
#        buildkitd-flags: '"--progress ''plain''"'

    # -
    #   name: Cache Docker layers
    #   uses: actions/cache@v4
    #   with:
    #     path: /tmp/.buildx-cache
    #     key: ${{ runner.os }}-${{ env.DistroCodeName }}
    #     # restore-keys: ${{ runner.os }}-${{ github.repository }}-${{ github.ref_name }}

    -
      name: Build and export to (local/private) registry
      uses: docker/build-push-action@v6
      with:
        file: tools/docker/${{ env.DistroCodeName }}/Dockerfile
        # outputs: type=cacheonly # build without pushing
        push: true
        tags: ${{ steps.compose-image-tag.outputs.EE_Distro_tag }}:latest
        # target: custom
        no-cache: false
        cache-from: type=registry,ref=${{ steps.compose-image-tag.outputs.EE_Distro_tag }}:buildcache
        cache-to: type=registry,ref=${{ steps.compose-image-tag.outputs.EE_Distro_tag }}:buildcache,mode=max
        # cache-from: type=registry,ref=${{ vars.DOCKER_HUB_USERNAME }}/${{ vars.DOCKER_HUB_IMAGE_NAME }}.1:buildcache
        # cache-to: type=registry,ref=${{ vars.DOCKER_HUB_USERNAME }}/${{ vars.DOCKER_HUB_IMAGE_NAME }}.1:buildcache,mode=max
        # cache-from: type=local,src=/tmp/.buildx-cache
        # cache-to: type=local,mode=max,dest=/tmp/.buildx-cache-new
        # cache-from: type=local,src=${{ runner.temp }}/.buildx-cache
        # cache-to: type=local,dest=${{ runner.temp }}/.buildx-cache-new,mode=max
        build-args: |
          USER_UID=${{ steps.get-docker-guid.outputs.docker-guid }}
#          --progress=plain
#          DOCKER_BUILDKIT=0

    # - # Temp fix to prevent cache size keeps growing
    #   # https://docs.docker.com/build/ci/github-actions/cache/#local-cache
    #   name: Move cache
    #   run: |
    #     rm -rf /tmp/.buildx-cache
    #     mv /tmp/.buildx-cache-new /tmp/.buildx-cache
