---
name: Build prebuilt toolchain image

on:
  # push:
  #   paths:
  #     - 'packages/**'
  #     - 'tools/docker/noble/**'
  workflow_dispatch: # yamllint disable-line rule:truthy
    inputs:
      runner:
        description: 'Runner to run against'
        required: true
        type: choice
        options:
          - self-hosted
          - github
        default: self-hosted
      os:
        description: 'OS codename'
        required: true
        type: choice
        options:
          - bookworm
          - jammy
          - noble
          - noble-custom
          - plucky
          - questing
          - sid
        default: noble
      arch:
        description: 'Arch of build target'
        required: true
        type: choice
        options:
          - amd64
          - aarch64
          - arm
          - x86_64
        default: aarch64
      debug:
        description: 'Enable debug build'
        required: true
        type: boolean
        default: false

run-name: ${{ format('{0} ({1}/{2}/{3}{4})', github.workflow, inputs.runner || 'self-hosted', inputs.os || 'noble', inputs.arch || 'aarch64', inputs.debug && '/debug' || '') }}

defaults:
  run:
    shell: bash

jobs:
  yamllint:
    runs-on: ${{ (inputs.runner == 'github' && 'ubuntu-latest' || inputs.runner) || 'self-hosted' }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Run yamllint composite action
        uses: ./.github/actions/composite/yamllint
        with:
          # yamllint_config_data: '{extends: default, rules: {line-length: disable}}'  # Optionally set yamllint config data
          yamllint_config_data: |
            extends: default
            rules:
              document-start: disable
              line-length: disable
              comments:
                min-spaces-from-content: 1
          yamllint_config_file: ''  # Optionally set to .yamllint or another config file
          yamllint_files_or_dirs: './.github/workflows/prebuild-EddictwareELEC.yml'
          # yamllint_files_or_dirs: '**/*.yml **/*.yaml'  # Optionally override file globs

  build:
    runs-on: ${{ (inputs.runner == 'github' && 'ubuntu-latest' || inputs.runner) || 'self-hosted' }}
    needs: yamllint
    permissions:
      contents: read
      packages: write
    env:
      IMAGE_NAME: eddictwareelec-prebuilt
      EE_REGISTRY: ghcr.io
      EE_REGISTRY_OWNER:
      EE_Distro: EddictwareELEC
      EE_Project: RPi
      EE_Device: RPi4
      EE_Arch: ${{ inputs.arch || 'aarch64' }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Set up QEMU (for cross-platform build)
        uses: docker/setup-qemu-action@v4

      - name: Log in to GHCR
        uses: docker/login-action@v4
        with:
          registry: ${{ env.EE_REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Correct Repository Owner casing in Image Tag
        id: correct-repo-owner-tag
        run: |
          registry_owner="${{ github.repository_owner }}"
          echo "EE_REGISTRY_OWNER=${registry_owner,,}" | sudo tee -a $GITHUB_ENV

      # - name: Set up Docker Buildx (container driver)
      #   uses: docker/setup-buildx-action@v4
      #   with:
      #     driver: docker-container
      #     buildkitd-flags: ${{ inputs.debug && '--debug' || '' }}

      - name: Build and push prebuilt image
        uses: docker/build-push-action@v7
        with:
          context: .
          file: tools/docker/${{ inputs.os }}-custom/prebuilt-toolchain.Dockerfile
          platforms: linux/amd64
          # platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ${{ env.EE_REGISTRY }}/${{ env.EE_REGISTRY_OWNER }}/${{ env.IMAGE_NAME }}:${{ inputs.os }}-${{ inputs.arch }}
          build-args: |
            DISTRO=${{ env.EE_Distro }}
            PROJECT=${{ env.EE_Project }}
            DEVICE=${{ env.EE_Device }}
            ARCH=${{ env.EE_Arch }}

      # Ensure ownership alignment for the build directory
      - name: Fix permissions for build directory
        run: |
          # Check if the directory exists, create it if not
          BUILD_DIR="/build/build.${{ env.EE_Distro }}-${{ env.EE_Device }}.${{ env.EE_Arch }}-13.0-devel"
          if [ ! -d "$BUILD_DIR" ]; then
            echo "Directory does not exist. Creating it..."
            sudo mkdir -p "$BUILD_DIR"
          fi

          sudo chown -R $DOCKER_UID:$DOCKER_GID "$BUILD_DIR" || true

          # Add diagnostics to verify ownership and permissions
          echo "=== Ownership and Permissions Diagnostics ==="
          ls -ld "$BUILD_DIR"
          find "$BUILD_DIR" -maxdepth 2 -exec stat -c "%U:%G %a %n" {} \;
