name: Docker Container Action to build EddictwareELEC

on:
  workflow_dispatch:

env:
  DISABLE_COLORS: yes
  LOGCOMBINE: fail
  MTIMMEDIATE: no
  DEBUG: yes
  MTDEBUG: yes
  MTVERBOSE: yes
  MTPROGRESS: yes
  DISTRO: EddictwareELEC
  PROJECT: RPi
  DEVICE: RPi4
  ARCH: aarch64
  BUILDER_NAME: ${{ github.repository_owner }}
  BUILD_BASE: "alt.build.noble"

jobs:
  hello_world_job:
    runs-on: blacksmith-4vcpu-ubuntu-2404 #blacksmith-4vcpu-ubuntu-2404 #self-hosted 
    name: A test job to build in a noble container
    env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Checkout
        uses: actions/checkout@v5
        with:
          set-safe-directory: true #${{ github.workspace }}

      - name: overwrite some repo files
        id: overwrite-repo-files
        shell: bash
        run: |
          sed -i 's/USER docker/# USER docker/g' tools/docker/noble/Dockerfile
          # sed -i 's/# ENTRYPOINT \[\]/ENTRYPOINT \["\/bin\/sh", "-c", "git config --global --add safe.directory \/github\/workspace && make image"\]/g' tools/docker/noble/Dockerfile
          sed -i 's/"\${EUID}" -eq 0/"\${EUID}" -eq -1/g' config/options
          # cat tools/docker/noble/Dockerfile

          # git config --global user.name '${{ github.repository_owner }}'
          # git config --global user.email '${{ github.actor_id }}+${{ github.actor }}@users.noreply.github.com'
          # git config --global --add safe.directory ${{ github.workspace }}
          # git config --global --add safe.directory '/github/workspace'
          # cat config/options

      - name: Set BUILDER_VERSION
        id: set-builder-version
        shell: bash
        run: echo "BUILDER_VERSION=13.0-$(date +%Y%m%d)" | sudo tee -a $GITHUB_OUTPUT

      - name: make action step
        uses: ./.github/actions/container-actions/noble
        id: make-step
        with:
          make-args: '$(make image)'
          gh-token: ${{ env.GH_TOKEN }}
          disable-colors: ${{ env.DISABLE_COLORS }}
          logcombine: ${{ env.LOGCOMBINE }}
          mtimmediate: ${{ env.MTIMMEDIATE }}
          debug: ${{ env.DEBUG }}
          mtdebug: ${{ env.MTDEBUG }}
          mtverbose: ${{ env.MTVERBOSE }}
          mtprogress: ${{ env.MTPROGRESS }}
          distro: ${{ env.DISTRO }}
          project: ${{ env.PROJECT }}
          device: ${{ env.DEVICE }}
          arch: ${{ env.ARCH }}
          builder-name: ${{ env.BUILDER_NAME }}
          builder-version: ${{ steps.set-builder-version.outputs.BUILDER_VERSION }}
          build-base: ${{ env.BUILD_BASE }}
