name: Test the best/shortest runner logic

on:
  workflow_dispatch:
    inputs:
      runner:
        description: 'Runner to run against'
        required: true
        type: choice
        options:
          - self-hosted
          - github
          - blacksmith
        default: self-hosted

defaults:
  run:
    shell: bash

jobs:
  runner:
    name: Output workflow runner
    # runs-on cannot access environment context, so we have to set the logic here and then output
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: read
      attestations: read
      id-token: write
    outputs:
      runner: >-
        ${{
          inputs.runner == 'github' && 'ubuntu-latest' ||
          inputs.runner == 'blacksmith' && 'blacksmith-8vcpu-ubuntu-2404' ||
          inputs.runner
        }}
